# Generated by Django 5.0.3 on 2024-04-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_category_alter_stock_category_alter_stock_issue_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.category'),
        ),
    ]
